.TH "METALINK_DELETE" "3" "July 2012" "libmetalink 0.1.0" "libmetalink Manual"
.SH "NAME"
metalink_delete \- Free the allocated resources for metalink_t structure.
.SH "SYNOPSIS"
.B #include <metalink/metalink.h>
.sp
.BI "void metalink_delete(metalink_t *" metalink );

.SH "DESCRIPTION"
\fBmetalink_delete\fP() frees the allocated resources for \fImetalink\fP.
Passing NULL is legal: \fBmetalink_delete\fP() does nothing in this case.

.SH "RETURN VALUE"
\fBmetalink_delete\fP() returns no value.

.SH "SEE ALSO"
.BR metalink_t (3)
